packages:
  - packages/*

allowBuilds:
  "@parcel/watcher": true
  vue-demi: true

minimumReleaseAgeExclude:
  - '@mcistudio/unoui-vue@1.1.1'

onlyBuiltDependencies:
  - "@parcel/watcher"
  - vue-demi
